name: Build and Deploy
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '23'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          cli: latest
          bb: latest

      - name: Cache clojure/java dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: ${{ runner.os }}-clojure-${{ hashFiles('**/*.edn') }}
          restore-keys: |
            ${{ runner.os }}-clojure-

      - name: Install node dependencies
        run: npm install

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Build app
        run: |
          set -x
          npx shadow-cljs release mini

      - name: Run script with node
        run: |
          set -x
          node dist/script.js
